[package]
name = "doodle_example"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde_json = "1.0.0"
doodle = { path = "../doodle" }
